version: '3'

services:

  broker-services:
    build:
      context: ./../broker-service #source code folder
      dockerfile: ./../broker-service/broker-service.dockerfile
    restart: always
    ports:
      - "8088:80" #localhost : docker service
    deploy:
      mode: replicated
      replicas: 1
  
  authentication-service:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/authentication-service.dockerfile
    restart:
      always
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"
      #using postgres container port
      #if using localhost we can use host=postgres and port and 5454
  postgres:
    image: 'postgres:14.0'
    ports:
      - "5454:5432" #localhost : docker service
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/ #localhost : docker container